package com.innovasphere.enums;

public enum NotificationType {
    JOIN_REQUEST,
    JOIN_REQUEST_ACCEPTED,
    JOIN_REQUEST_REJECTED,
    TEAM_INVITATION,
    TEAM_INVITATION_ACCEPTED,
    TEAM_INVITATION_REJECTED,
    MENTORSHIP_REQUEST,
    MENTORSHIP_ACCEPTED,
    MENTORSHIP_REJECTED,
    PROJECT_UPDATE,
    SYSTEM
}